# YAML for linux DQN configuration

train:
  max_episode_length: 5000
  num_episodes: 10000
  batch_size: 32
  max_replay_len: 10000
  model_file: "dqn_model.h5"
  train_period: 5
  train_after_episode: False

inference:
  only_inference: False
  num_inference_episodes: 10

gpu:
  device: 0 #-1 means use cpu


system: 
  os: "linux"
  arch: "x86_64"
  drone_sim: "drone_sim_external_linux_headless"

#TODO add model specific params
